version: '3'

services:
  php:
    hostname: php
    build:
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./docker/php.conf:/etc/supervisor/conf.d/php.conf
      - ./docker/log/supervisor:/var/log/supervisor
      - ./docker/php.ini:/usr/local/etc/php/php.ini
      - ./:/var/www
    environment:
      TZ: "Asia/Shanghai"
      LANG: "C.UTF-8"
    links:
      - redis
      - mariadb
    depends_on:
      - redis
      - mariadb
    restart: unless-stopped

  nginx:
    image: "nginx:alpine"
    ports:
      - "${APP_PORT}:80"
      - "${APP_PORT_SSL}:443"
    volumes:
      - ./docker/site.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    links:
      - php
    depends_on:
      - php
    restart: unless-stopped

  redis:
    hostname: redis
    image: "redis:alpine"
    volumes:
      - ./docker/redis:/data
    environment:
      TZ: "Asia/Shanghai"
    restart: unless-stopped

  mariadb:
    hostname: mariadb
    image: "bitnami/mariadb"
    volumes:
      - ./docker/mariadb:/bitnami/mariadb
    environment:
      - "MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}"
      - "MARIADB_DATABASE=${DB_DATABASE}"
      - "MARIADB_USER=${DB_USERNAME}"
      - "MARIADB_PASSWORD=${DB_PASSWORD}"
    restart: unless-stopped
